apiVersion: v1
kind: Service
metadata:
  name: immich-service
  namespace: immich
spec:
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: immich
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 2283
